DROP TABLE IF EXISTS MAP;

DROP TABLE IF EXISTS WEAPON;

DROP TABLE IF EXISTS SKIN;

DROP TABLE IF EXISTS AGENT;

DROP TABLE IF EXISTS USR;

CREATE TABLE MAP(
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(20) NOT NULL,
DESCRIPTION VARCHAR(1000) NOT NULL,
BOMBSITES INT NOT NULL,
COORDINATES VARCHAR(50) NOT NULL,
COUNTRY VARCHAR(50) NOT NULL,
PECULIARITY VARCHAR(50),
RELEASE_DATE DATE NOT NULL,
SEASON INT NOT NULL,
ACT INT NOT NULL,
ROTATION BOOLEAN NOT NULL,
PATH VARCHAR(100) NOT NULL
);

CREATE TABLE SKIN(
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(50) NOT NULL,
DATE DATE NOT NULL,
PRICE FLOAT NOT NULL,
SEASON INT NOT NULL,
ACT INT NOT NULL,
RECOLORS INT NOT NULL,
PATH VARCHAR(100) NOT NULL
);

CREATE TABLE AGENT(
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(20) NOT NULL,
ROLE VARCHAR(20)NOT NULL,
LORE VARCHAR(200) NOT NULL,
SKILLQ VARCHAR(50) NOT NULL,
SKILLE VARCHAR(50) NOT NULL,
SKILLC VARCHAR(50) NOTNULL,
ULTIMATE VARCHAR(50) NOT NULL,
SKILDESCRIPTIONQ VARCHAR(1000) NOT NULL,
SKILLDESCRIPTIONE VARCHAR(1000) NOT NULL,
SKILLDESCRIPTIONC VARCHAR(1000) NOT NULL,
ULTIMATEDESCRIPTION VARCHAR(1000) NOT NULL,
ULTIMATEPOINTS INT NOT NULL,
PATH VARCHAR(100) NOT NULL
);

CREATE  TABLE USR (
ID INT PRIMARY KEY AUTO_INCREMENT,
USERNAME VARCHAR(50) NOT NULL,
PASSWORD VARCHAR(50) NOT NULL
);